version: '2'
services:
    gateway-app:
        image: gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    
    phoneservice-app:
        image: phoneservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@phoneservice-oracle:1521:phoneservice
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=phoneservice-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
    phoneservice-oracle:
        image: sath89/oracle-12c:latest
        environment:
            - DBCA_TOTAL_MEMORY=1024
            - WEB_CONSOLE=true
    phoneservice-elasticsearch:
        image: elasticsearch:2.4.6
    
    uaa-app:
        image: uaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@uaa-oracle:1521:uaa
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=uaa-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=admin
    uaa-oracle:
        image: sath89/oracle-12c:latest
        environment:
            - DBCA_TOTAL_MEMORY=1024
            - WEB_CONSOLE=true
    uaa-elasticsearch:
        image: elasticsearch:2.4.6
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
